name: Hola mundo

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "*/5 *  * * *"   #se ejecuta cada 5 minutos
  push:
     branches:
       - main
  
  pull_request:
    branches:
      - main
jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "Hola Mundo Marcial"

      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Listar los archivos del repositorrio
        run:
          echo "El rpositorio ${{ github.repository}} contiene los siguientes archivos:"
          tree
        
        
  
